type = "Quest"
quest = "The Lost Tribe"

[[messages]]
text = "I heard rumors there was something going on below Lumbridge Castle."

[[messages]]
text = "The duke is sure to know more about this. Why not speak with him?"

[[requirements]]
type = "Members"

[[requirements]]
type = "Quest"
name = "Goblin Diplomacy"
status = "complete"

[[requirements]]
type = "Quest"
name = "Rune Mysteries"
status = "complete"

[[requirements]]
type = "Skill"
name = "Agility"
level = 13

[[requirements]]
type = "Skill"
name = "Thieving"
level = 13

[[requirements]]
type = "Skill"
name = "Mining"
level = 17
