type = "Combat"

[[messages]]
text = "Vannaka can give you a slayer task."

[[messages]]
text = "He's in the Edgeville Dungeon, west of Varrock."

[[messages]]
text = "If you find a brass key, you can enter the dungeon from the locked house west of the cooking guild."

[[requirements]]
type = "Skill"
name = "Combat"
level = 40
levelMax = 128
