type = "Item"
itemType = "Weapon"

[[messages]]
text = "Whips are a great weapon."

[[messages]]
text = "You can get one from the Grand Exchange or from an Abyssal Demon if you have the slayer level."
if = "not ironman"

[[messages]]
text = "You can get one from an Abyssal Demon."
if = "ironman"

[[requirements]]
type = "Members"

[[requirements]]
type = "Skill"
name = "Attack"
level = 70

[[requirements]]
type = "Skill"
if = "ironman"
name = "Slayer"
level = 85
