type = "Money"
messages = [
  "You can probably craft gold rings for a profit.",
  "Just buy gold bars from the Grand Exchange and then craft them using the Edgeville furnace.",
  "You can sell them to Grum's exchange in Port Sarim or the Grand Exchange."
]

[[requirements]]
type = "NotIronMan"

[[requirements]]
type = "Skill"
name = "Crafting"
level = 5
levelMax = 99
