type = "Money"

[[messages]]
text = "You can probably craft gold rings for a profit."

[[messages]]
text = "Just buy gold bars from the Grand Exchange and then craft them using the Edgeville furnace."

[[messages]]
text = "You can sell them to Grum's exchange in Port Sarim or the Grand Exchange."

[[requirements]]
type = "NotIronMan"

[[requirements]]
type = "Skill"
name = "Crafting"
level = 5
levelMax = 99
