type = "Money"
messages = [
  "You can craft cannonballs for a profit.",
  "Just buy steel bars from the Grand Exchange and then smith them using the Edgeville furnace.",
  "You can sell them back to the Grand Exchange."
]

[[requirements]]
type = "NotIronMan"

[[requirements]]
type = "Skill"
name = "Smithing"
level = 35
levelMax = 99

[[requirements]]
type = "Quest"
name = "Dwarf Cannon"
minimum = "in progress"
