type = "Money"

[[messages]]
text = "You can probably craft sapphire rings for a profit."

[[messages]]
text = "You can buy gold bars and cut sapphires and then craft them using the Edgeville furnace."

[[messages]]
text = "Once you craft them, cast the high alchemy spell on them. You can do it on their bank notes."

[[requirements]]
type = "Skill"
name = "Crafting"
level = 20
levelMax = 99

[[requirements]]
type = "Skill"
name = "Magic"
level = 55
levelMax = 99
