type = "Money"
messages = [
  "You can probably craft sapphire rings for a profit.",
  "Just buy gold bars and cut sapphires from the Grand Exchange and then craft them using the Edgeville furnace.",
  "You could make even more money by casting High Alchemy if you were to get your magic skill up to level 55."
]

[[requirements]]
type = "NotIronMan"

[[requirements]]
type = "Skill"
name = "Crafting"
level = 20
levelMax = 99

[[requirements]]
type = "Skill"
name = "Magic"
level = 1
levelMax = 54
