name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in the repository
        run: find . -name '*.yml' -not -path "./.github/*" > ./filenames.txt
      - name: Merge yml files
        run: |
          cat filenames.txt | while read line 
          do
            echo "---" >> merged.yml
            cat $line >> merged.yml
          done
          cat merged.yml
      - name: Create Release and Upload Asset with gh cli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          gh release delete Latest
          echo "Creating release"
          gh release create $calculatedSha \
            --title "$calculatedSha" \
            --notes "Release created from tag ${{ github.ref }}" \
            merged.yml # Upload the artifact during creation
          gh release create Latest \
            --title "${{ github.ref }}" \
            --notes "Release created from tag ${{ github.ref }}" \
            merged.yml # Upload the artifact during creation
